name: Release Solar3d Page

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build-and-deploy:
    name: 构建部署
    runs-on: ubuntu-latest
    steps:
      - name: 切换分支
        uses: actions/checkout@v4
      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
      - name: 安装依赖
        run: yarn
      - name: 构建项目
        run: yarn build
      - name: 部署到服务器
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.SSH_REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.SSH_SERVER_USER }}
          SOURCE: "dist/"
          TARGET: ${{ secrets.SERVER_TARGET }}
          SCRIPT_BEFORE: "bash ${{ secrets.SERVER_DIR_SCRIPT }} ${{ secrets.SERVER_TARGET }}"
